.\"
.\" Copyright (c) 2006 Itronix Inc.
.\" All rights reserved.
.\"
.\" Written by Iain Hibbert for Itronix Inc.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of Itronix Inc. may not be used to endorse
.\"    or promote products derived from this software without specific
.\"    prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY ITRONIX INC. ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL ITRONIX INC. BE LIABLE FOR ANY
.\" DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\" ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd December 21, 2019
.Dt BCMFW 8
.Os
.Sh NAME
.Nm bcmfw
.Nd firmware loader for Broadcom chip based Bluetooth adaptors
.Sh SYNOPSIS
.Nm
.Op Fl qv
.Op Fl f Qq Ar BCM2033 firmware
.Op Fl m Qq Ar BCM2033 mini-driver
.Op Ar device Ar ...
.Lp
.Nm bcmfw-install
.Op source-directory
.Sh DESCRIPTION
Modern Broadcom chips find their initial firmware instructions from
an internal PROM after power up.
This initial firmware is usually enough for proper functionality but,
once running,
.Nm
can upgrade it over the HCI interface with
.Qq Patch RAM
data files provided by Broadcom.
.Nm
probes all adaptors connected to the Bluetooth protocol stack unless
any are specified on the commandline, in which case only those are probed.
The probe first checks the Manufacturer code with the standard
.Qq Read Local Version
command, and only when it is 15
.Pq Broadcom
does it attempt to check the device itself, with vendor-specific commands.
.Pp
Because the device will need to be reset afterwards, and to prevent errors
in a running system, no update will be attempted unless
.Nm
found the device in a non-enabled state.
.Pp
Older BCM2033 based devices do not have firmware and will not initially be
configured as Bluetooth adaptors, so will attach as
.Xr ugen 4 .
If a
.Ar ugen
device name is passed on the commandline,
.Nm
checks the USB Vendor & Product ID's directly before proceeding, which
should be 0x0a5c and 0x2033 respectively.
.Pp
The options are as follows:
.Bl -tag -width 12345678
.It Fl f Ar firmware
Specify alternate firmware file for BCM2033 devices.
The default name is
.Pa BCM2033-FW.bin
.It Fl m Ar mini-driver
Specify alternate mini-driver file for BCM2033 devices.
The default name is
.Pa BCM2033-MD.hex
.It Fl q
Be quiet in normal use.
.It Fl v
Be more verbose while operating.
.El
.Pp
The Patch RAM files are not available directly from Broadcom but since
Feb 2017 are supplied via the Microsoft Windows Update Service and can be
found at:
.Lp
.Li Sy https://www.catalog.update.microsoft.com/Search.aspx?q=Broadcom+Bluetooth
.Lp
The latest version available at this time is 12.0.1.1012,
download this .cab archive, and extract to a temporary directory.
There should be many
.Qq .hex
files and an
.Qq .inf
file, and the
.Nm bcmfw-install
program can be used to install firmware files and an index to your
.Nx
filesystem.
.Pp
After a successful update, the HCI revision of the device will change.
.Sh FILES
.Bl -tag -width ".Pa /dev/ugen Ns Ar N Ns Pa \&. Ns Ar EE X " -compact
.It Pa /libdata/bcmfw/*
.It Pa /dev/ugen Ns Ar N Ns Pa \&. Ns Ar EE
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr bluetooth 4 ,
.Xr ugen 4
.Sh AUTHORS
.An Iain Hibbert
for Itronix, Inc.
